variable "vm_template_id" {}
variable "tags" {}
variable "vm_name" {}
variable "target_node" {}
variable "vm_cores" {}
variable "vm_memory" {}
variable "disk_size" {}
variable "disk_storage" {}
variable "network_bridge" {}
variable "ssh_public_keys" {}
variable "vm_username" {}
variable "vm_password" {}